// Code generated by MockGen. DO NOT EDIT.
// Source: story.go
//
// Generated by this command:
//
//	mockgen -source=story.go -destination=mocks/mock.go
//

// Package mock_story is a generated GoMock package.
package mock_story

import (
	context "context"
	reflect "reflect"

	domain "github.com/orgball2608/insta-parser-telegram-bot/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, user domain.Story) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, user)
}

// GetByID mocks base method.
func (m *MockRepository) GetByID(ctx context.Context, id int) (*domain.Story, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Story)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepository)(nil).GetByID), ctx, id)
}

// GetByStoryID mocks base method.
func (m *MockRepository) GetByStoryID(ctx context.Context, storyID string) (*domain.Story, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByStoryID", ctx, storyID)
	ret0, _ := ret[0].(*domain.Story)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByStoryID indicates an expected call of GetByStoryID.
func (mr *MockRepositoryMockRecorder) GetByStoryID(ctx, storyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByStoryID", reflect.TypeOf((*MockRepository)(nil).GetByStoryID), ctx, storyID)
}
