version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: insta-parser-bot
    restart: unless-stopped
    # Ánh xạ cổng từ máy chủ (host) sang container
    # HOST:CONTAINER
    # Cổng trong container là 8080 (theo Dockerfile)
    # Cổng trên máy chủ bạn có thể tùy chọn, ví dụ 8081
    ports:
      - "8081:8080"
    # Sử dụng env_file để tải tất cả biến môi trường từ file .env
    # Điều này giúp file compose sạch sẽ và bảo mật hơn.
    env_file:
      - .env
    # Đảm bảo app chỉ khởi động sau khi postgres đã sẵn sàng
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    container_name: insta-parser-postgres
    restart: unless-stopped
    # Các biến môi trường cho postgres sẽ được lấy từ file .env
    # Docker Compose sẽ tự động thay thế ${VAR_NAME} bằng giá trị trong .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
      # Chỉ mở cổng này ra ngoài nếu bạn cần kết nối vào DB từ máy của mình
      # Nếu không, hãy comment dòng này lại để tăng bảo mật.
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: insta-parser-redis
    restart: unless-stopped
    ports:
      # Tương tự postgres, chỉ mở nếu cần truy cập từ bên ngoài
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
