version: '3.9'
services:
  app:
    image: waang07/instagram-notifier:latest
    restart: always
    networks:
      - app-tier
    env_file:
      - ./.env

  postgres:
    image: "postgres:14"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty123
      - POSTGRES_DB=postgres
    ports:
      - "54320:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app-tier
    restart: always

networks:
  app-tier:
    driver: bridge
