version: '3.8'
services:
  app:
    image: waang07/instagram-notifier:latest
    restart: always
    networks:
      - app-tier
    env_file:
      - ./.env

  postgres:
    image: postgres:15
    ports:
      - "54326:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
        - app-tier

volumes:
  postgres:

networks:
  app-tier:
    driver: bridge
