version: '3.9'
services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - app-tier

  postgres:
    image: "postgres:14"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty123
      - POSTGRES_DB=postgres
    ports:
      - "54320:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app-tier
    restart: always

networks:
  app-tier:
    driver: bridge
