name: Build and push

on:
  push:
    branches:
      - v2
  workflow_dispatch:

jobs:
  container-security-check:
    name: container-security-check
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-docker]')"
    uses: ./.github/workflows/container_security_check.yml
    secrets: inherit
    with:
      image-name: ${{ github.event.repository.name }}

  build-and-push:
    needs: container-security-check
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-docker]')"
    runs-on: ubuntu-latest

    outputs:
      IMAGE_NAME_LOWER: ${{ steps.prepare.outputs.image_name_lower }}

    steps:
      - name: Prepare image name
        id: prepare
        run: echo "image_name_lower=$(echo ${{ vars.IMAGE_NAME }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Dockerhub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.prepare.outputs.image_name_lower }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.prepare.outputs.image_name_lower }}:latest
            ${{ steps.prepare.outputs.image_name_lower }}:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
