name: Container security check
on:
  workflow_call:
    inputs:
      working-directory:
        description: working directory
        type: string
        required: false
        default: "./"
      image-name:
        description: container image name to check by Trivy and Dockle
        type: string
        required: true

env:
  IMAGE_TAG: tmp

jobs:
  security-check:
    name: Dockle & Trivy
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Prepare image name
        id: prepare
        run: echo "image_name_lower=$(echo ${{ inputs.image-name }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build an image from Dockerfile
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.working-directory }}
          load: true
          tags: |
            ${{ steps.prepare.outputs.image_name_lower }}:${{ env.IMAGE_TAG }}

      - name: Install Dockle
        run: |
          VERSION=$(
            curl --silent "https://api.github.com/repos/goodwithtech/dockle/releases/latest" | \
            grep '"tag_name":' | \
            sed -E 's/.*"v([^"]+)".*/\1/' \
            ) && curl -L -o dockle.deb https://github.com/goodwithtech/dockle/releases/download/v${VERSION}/dockle_${VERSION}_Linux-64bit.deb
          sudo dpkg -i dockle.deb && rm dockle.deb

      - name: Security check by Dockle
        run: |
          dockle -f txt \
            -o ${{ inputs.working-directory }}dockle-result.txt \
            -i ${{ inputs.working-directory }}.dockleignore \
            ${{ steps.prepare.outputs.image_name_lower }}:${{ env.IMAGE_TAG }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.prepare.outputs.image_name_lower }}:${{ env.IMAGE_TAG }}
          format: 'table'
          output: ${{ inputs.working-directory }}/trivy-result.txt
          ignore-unfixed: true
          timeout: 10m

      - name: add comment file
        run:  echo "## Container security check" > comment.md

      - name: add dockle result to comment file
        run: |
          echo "### dockle" >> comment.md
          echo \`\`\` >> comment.md
          cat dockle-result.txt | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g" >> comment.md
          echo \`\`\` >> comment.md

      - name: add trivy result to comment file
        run: |
          echo "### trivy" >> comment.md
          echo \`\`\` >> comment.md
          cat trivy-result.txt >> comment.md
          echo \`\`\` >> comment.md

      - name: Hide the previous comment and add a comment at the end
        uses: marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31 #v2.9.0
        with:
          hide_and_recreate: true
          hide_classify: "OUTDATED"
          path: comment.md
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
